In [2]:
import requests

In [3]:
URL = "https://stephen-king-api.onrender.com/api/books"

res = requests.get(URL)

In [4]:
res

In [7]:
json_data = res.json()

In [11]:
import pandas as pd

df = pd.json_normalize(json_data["data"])
df = df[['id', 'Title', 'Year', 'ISBN']]

In [12]:
df

    id          Title  Year               ISBN
0    1         Carrie  1974  978-0-385-08695-0
1    2    Salem's Lot  1975  978-0-385-00751-1
2    3    The Shining  1977  978-0-385-12167-5
3    4           Rage  1977  978-0-451-07645-8
4    5      The Stand  1978  978-0-385-12168-2
..  ..            ...   ...                ...
58  59   The Outsider  2018  978-1-50118-098-9
59  60      Elevation  2018  978-1-98210-231-9
60  61  The Institute  2019  978-1-98211-056-7
61  62          Later  2021  978-1-78909-649-1
62  63  Billy Summers  2021  978-1-982-17361-6

[63 rows x 4 columns]

In [13]:
# Web Scraping

import requests

URL = "https://www.scrapethissite.com/pages/simple"
res = requests.get(URL)

print(res.status_code)

200

In [14]:
res

In [17]:
if res.status_code == 200:
    print(res.headers)

with open("scraped_data/data1.html", "w", encoding="utf-8") as f:
    f.write(res.text)

{'Date': 'Sat, 18 Apr 2026 08:28:27 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=pfcStV%2Fd1BXFr0TFhjFgoDSlisyBNkrXiPGl7sXHnGc%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1776500906"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=pfcStV%2Fd1BXFr0TFhjFgoDSlisyBNkrXiPGl7sXHnGc%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1776500906"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'zstd', 'CF-RAY': '9ee24bcb6b735fd0-MRS', 'alt-svc': 'h3=":443"; ma=86400'}

In [2]:
pip install beautifulsoup4

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install lxml

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lxml in c:\programdata\anaconda3\lib\site-packages (5.3.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
# BeautifulSoup

from bs4 import BeautifulSoup

with open("scraped_data/data1.html", "r") as f:
    html_content = f.read()

soup = BeautifulSoup(html_content, "lxml")

In [29]:
all_h3 = soup.find_all("h3")

#type(all_h3)

all_countries = []

for h3 in all_h3:
    name = h3.get_text(strip=True)
    # print(h3.find_parent("div")["class"])

    population = h3.find_next("div").select("span.country-population")[0].get_text(strip=True)
    print(h3.find_next("div").select_one("span.country-population").get_text(strip=True))

    # print(h3.attrs)

    all_countries.append([name, population])

84000
4975593
29121286
86754
13254
2986952
2968000
13068161
0
41343201
57881
8205000
21515754
71566
26711
8303512
4590000
285653
156118464
10403000
16241811
7148785
738004
9863117
9056010
8450
65365
395027
9947418
18012
201103330
301790
699847
0
2029307
9685000
314522
33679000
628
70916439
4844927
3039126
7581000
21058798
21388
16746491
19294149
1330044000
47790000
4516220
11423000
508659
141766
1500
1102677
10476000
81802257
740528
5484000
72813
9823821
34586184
14790608
1291170
80471869
273008
5792984
46505963
88013491
5244000
875983
2638
107708
48228
64768389
1545255
62348447
107818
4630000
195506
65228
24339838
27884
56375
1593256
10324025
443000
1014999
11000000
30
13550440
159358
1565126
748486
6898686
0
7989415
4491000
9648924
9982000
242968342
4622917
7353985
75049
1173108018
4000
29671605
76923300
308910
60340328
90812
2847232
6407085
127288000
40046566
5776500
14453680
92533
773407
51134
22912177
48422644
2789132
44270
15340000
6368162
4125247
160922
35000
21513990
3685076
1919552
2944459
497538
2217969
6461454
31627428
32965
4324000
666730
35925
21281844
65859
2062294
13796354
53414374
3086918
449198
53883
432900
3205060
9341
403000
1294104
395650
15447500
112468855
28274729
22061451
2128471
216494
15878271
1828
154000000
5995928
16645000
5009150
28951852
10065
2166
4252277
2967717
3410676
29907003
270485
6064515
99900177
184404791
38500000
7012
46
3916632
3800000
10676000
19907
6375830
840926
776948
21959278
7344847
140702000
11055976
25731776
559198
88340
35000000
9828655
4701069
7460
2007000
2550
5455000
5245695
31477
12323252
10112453
492829
8260490
175808
6052064
37429
22198110
1354051
20556
10543464
140
6587239
67089500
7487489
1466
1154625
4940916
10589025
122580
77804122
1228691
10472
22894384
41892895
45415596
33398682
0
310232863
3477000
27865738
921
104217
27223228
21730
108708
89571130
221552
16025
192001
1800000
23495361
159042
49000000
13460305
11651858

In [33]:
import pandas as pd

df = pd.DataFrame(all_countries, columns=["Name", "Population"])

In [34]:
df

                     Name Population
0                 Andorra      84000
1    United Arab Emirates    4975593
2             Afghanistan   29121286
3     Antigua and Barbuda      86754
4                Anguilla      13254
..                    ...        ...
245                 Yemen   23495361
246               Mayotte     159042
247          South Africa   49000000
248                Zambia   13460305
249              Zimbabwe   11651858

[250 rows x 2 columns]

In [35]:
df.to_csv("cleaned_data/data.csv", index=False)